### PR TITLE
Feature/shutdown error log

### PR DESCRIPTION
**Pull request by membphis**
check shutdown error log

### CODE REVIEW

**Comment by membphis** [comment]
@doujiang24 please take a review when you have time.

**Comment by lixianliang** [comment]
@membphis this pr can committing as soon as possible?

**Comment by agentzh** [comment]
@membphis Will you test various testing mode (HUP, check leak, valgrind, normal, stap, and etc) on your side with this new feature? It's also good to run `ngx_lua`'s test suite in those testing modes to be sure :) Thanks a lot!

**Comment by agentzh** [comment]
@lixianliang You are welcome to do as much testing as possible against this PR on your side, which can be very helpful.

**Comment by agentzh** [comment]
BTW, the official repos for Test::Nginx is here:

https://github.com/openresty/test-nginx

This is a fork.

**Comment by lixianliang** [comment]
@agentzh OK，I will do this.

**Pull request closed without merging**
